# service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: auth-service

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
