# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  progressDeadlineSeconds: 100
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        version: v10
    spec:
      containers:
        - image: ajoop/auth-service:v10
          imagePullPolicy: Always
          name: auth-service
          ports:
            - containerPort: 8083
