# service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: NodePort
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: auth-service
